// <auto-generated />
using HaereRa.API.DAL;
using HaereRa.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace HaereRa.API.Migrations
{
    [DbContext(typeof(HaereRaDbContext))]
    partial class HaereRaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("HaereRa.API.Models.ContactDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactDetailIdentifier")
                        .IsRequired();

                    b.Property<int>("NotificationProviderId");

                    b.Property<int>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationProviderId");

                    b.HasIndex("PersonId");

                    b.ToTable("ContactDetails");
                });

            modelBuilder.Entity("HaereRa.API.Models.ExternalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExternalAccountIdentifier")
                        .IsRequired();

                    b.Property<int>("ExternalPlatformId");

                    b.Property<bool>("IsPlatformManager");

                    b.Property<int>("IsSuggestionAccepted");

                    b.Property<int>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPlatformId");

                    b.HasIndex("PersonId");

                    b.ToTable("ExternalAccounts");
                });

            modelBuilder.Entity("HaereRa.API.Models.ExternalPlatform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PluginAssembly");

                    b.Property<string>("PluginAssemblyOptions");

                    b.HasKey("Id");

                    b.ToTable("ExternalPlatforms");
                });

            modelBuilder.Entity("HaereRa.API.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("HaereRa.API.Models.GroupMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<bool>("IsGroupManager");

                    b.Property<int>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PersonId");

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("HaereRa.API.Models.NotificationProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PluginAssembly");

                    b.Property<string>("PluginAssemblyOptions");

                    b.HasKey("Id");

                    b.ToTable("NotificationProviders");
                });

            modelBuilder.Entity("HaereRa.API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("KnownAs");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("HaereRa.API.Models.ContactDetail", b =>
                {
                    b.HasOne("HaereRa.API.Models.NotificationProvider", "NotificationProvider")
                        .WithMany("NotificationAccounts")
                        .HasForeignKey("NotificationProviderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HaereRa.API.Models.Person", "Person")
                        .WithMany("ContactDetails")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HaereRa.API.Models.ExternalAccount", b =>
                {
                    b.HasOne("HaereRa.API.Models.ExternalPlatform", "ExternalPlatform")
                        .WithMany("ExternalAccounts")
                        .HasForeignKey("ExternalPlatformId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HaereRa.API.Models.Person", "Person")
                        .WithMany("ExternalAccounts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HaereRa.API.Models.GroupMembership", b =>
                {
                    b.HasOne("HaereRa.API.Models.Group", "Group")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HaereRa.API.Models.Person", "Person")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
